package com.example.kengomaruyama.qiitaclient

import android.support.test.runner.AndroidJUnit4
import org.junit.Test
import org.junit.runner.RunWith
import java.lang.AssertionError

@RunWith(AndroidJUnit4::class)
class MainActivityTest{
    @Test
    fun test(){
        throw AssertionError("失敗するはず")
    }
}